[package]
name = "my_http"
version = "0.1.0"
authors = ["funkiben <funkiben@gmail.com>"]
edition = "2018"

[dependencies]
rustls = "0.18.0"
log = "0.4.11"
mio = { version = "0.7.0", features = ["os-poll", "tcp"] }
webpki = "0.21.0"